---
title: "A Hierarchical(Kriging) Bayesian Model vs A Hierarchical(Kriging) Model with R and Stan"
author: "Zelalem Araya (92797935) & Youjung Kim (3876269)"
date: "2024-04-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Working link to a public repo:
https://github.com/eunicekim919/STAT-447c-project.git

## Contributions of each team member:

## Introduction (Problem formulation)
In recent years, densely populated regions worldwide have experienced fluctuating crime rates due to various economic and environmental factors such as income, job availability, and climate. Historically, Vancouver has consistently had higher than expected about its population size and the average Canadian crime rate, including higher rates of violent crime. (Andresen, 2017; Statistics Canada, 2023) These rising crime rates prompt concerns about public safety, and how to appropriately allocate resources to adequately deal with issues unique to each area. Effective spatial analysis of crime data is crucial for understanding these patterns, predicting future occurrences, and implementing the right preventative measures. When reports are only available for certain regions, being able to interpolate available data spatially could provide important information without needing to expend unnecessary resources. Among the various statistical techniques, kriging offers a robust method of spatial interpolation using Bayesian optimization over a Gaussian process.

This study aims to analyze and compare different kriging models for interpolating crime density in Vancouver using reported crime data from the Vancouver Police Department GeoDASH Open Data, a source that provides aggregate crime data from the crime reports made in the City of Vancouver in 2022. (Vancouver Police Department, 2024). Both Stan and R are used to implement and assess the model, with the performance evaluated through Leave-One-Out Cross-Validation (LOO-CV). This technique assesses the model's predictive performance by leaving one observation out at a time and predicting its value using the rest of the data. Determining the most appropriate kriging model for this type of data & analysis has the potential to contribute to the greater field of geospatial crime analysis as a whole, informing policy decisions and strategic planning for crime reporting and urban safety management. Exploring a variety of kriging approaches, this paper also provides a better understanding of the advantages and disadvantages of the various kriging models. 
Kriging & Bayesian Foundations

  Kriging is the overarching term for a group of geostatistical techniques used for spatial interpolation, which estimate the values at unknown points based on the values of known points based on the values of the known points nearby - based on applications of Tobler’s first law. The foundation of kriging lies in its ability to model spatial autocorrelation through a semivariogram, a function that quantifies the strength of statistical correlation as a function of distance. This works by assuming that the distance between sample points reflects a quantifiable spatial correlation, that can then be used to interpolate values at unsampled locations. Kriging functions as a kind of Bayesian linear estimator, it works by incorporating some prior knowledge about the spatial processes, and then updating with the observed data to make predictions - the unknown values considered as random variables.

### Mathematical Explanation of Kriging
  Kriging leverages the spatial covariance among data points to make predictions at unsampled locations.
The key to kriging is the assumption that the spatial process underlying the observed data is a realization of a Gaussian process, consistent among all types of kriging methods. This process is governed by a mean function (often taken as constant or linear) and a covariance function, which quantifies how observations at different locations relate to one another based on their spatial separation.
	Below is a general mathematical overview of our current understanding of the method’s components. (Handcock & Stein, 1993; Webster & Oliver, 2007; Wiskotten et al., 2023)
	
The observed data $\mathbf{Z}$ are modeled as a realization of a Gaussian process:
$$Z(\mathbf{s}) = \mu(\mathbf{s}) + \epsilon(\mathbf{s})$$
where:
- $\mathbf{s}$ denotes a spatial location.
- $\mu(\mathbf{s})$ is the mean function, often assumed to be constant $\alpha$ across the space.
- $\epsilon(\mathbf{s})$ represents the spatially correlated random error, assumed to follow a multivariate normal distribution.
The core of a kriging model lies in its specification of the spatial covariance. A common choice is the exponential covariance function:
$$cov(Z(\mathbf{s}_i), Z(\mathbf{s}_j)) = \sigma^2 \exp\left(-\frac{\|\mathbf{s}_i - \mathbf{s}_j\|}{\rho}\right)$$
where:
- $\mathbf{s}_i - \mathbf{s}_j$ is the Euclidean distance between locations $\mathbf{s}_i$ and $\mathbf{s}_j$.
- $\sigma^2$ is the process variance.
- $\rho$ is the range parameter, influencing how quickly correlations decay with distance.

The prediction of $Z(\mathbf{s}_0)$ at a new location $\mathbf{s}_0$ using observed data $\mathbf{Z}$ at known locations $\mathbf{s}_1, \ldots, \mathbf{s}_N$ is given by:
$$\hat{Z}(\mathbf{s}_0) = \mu + \mathbf{k}^T \mathbf{K}^{-1} (\mathbf{Z} - \mu \mathbf{1})$$
where:
- $\mu$ is the assumed mean of the process.
- $\mathbf{Z}$ is the vector of observed values at the known locations.
- $\mathbf{k}$ is the vector of covariances between the new location \(\mathbf{s}_0\) and each of the known locations.
- $\mathbf{K}$ is the covariance matrix among the observed data points.
- $\mathbf{1}$ is a vector of ones (assuming a constant mean).

The components of $\mathbf{k}$ and $\mathbf{K}$ are computed using some covariance function:
$$\mathbf{k}[i] = \sigma^2 \exp\left(-\frac{\|\mathbf{s}_0 - \mathbf{s}_i\|}{\rho}\right)$$

$$\mathbf{K}[i,j] = \sigma^2 \exp\left(-\frac{\|\mathbf{s}_i - \mathbf{s}_j\|}{\rho}\right) + \sigma_{\text{err}}^2 \delta_{ij}$$
with $\delta_{ij}$ being the Kronecker delta, which is 1 if \(i = j\) and 0 otherwise, equivalent to the identity matrix in practice.

Finally, the model can also incorporate measurement error $\sigma_{\text{err}}^2$, which adds to the diagonal elements of the covariance matrix $\mathbf{K}$, representing error variance that is independent at each observed location.
Other Spatial Interpolation Methods
	Kriging is one of the most sophisticated geostatistical models, but others serve similar tasks - such as inverse distance weighting which computes the weighted average of nearby observed values or splines, which fit some smooth mathematical function that passes through the data points. However, kriging is often better for more complex given its semivariogram and allowing measures of uncertainty for those estimates. 
	
### Types of Kriging

Since Kriging is highly adaptive, various kinds can be used in different situations. Simple Kriging assumes a known constant mean throughout the entire region. Ordinary Kriging is the most common, it does not assume a known mean and instead estimates it based on available data. Universal kriging pushes the mean estimation further by modelling the mean as a polynomial function of coordinates, best for analyzing trends across a region.  (Mooney et al., 2018). Bayesian Kriging models incorporate spatial modeling utilizing a parametric function of distance that includes the longitude and latitude as random variables. (Zhang & Du, 2019)
Kriging Model Comparisons

While there are many types of kriging, determining which type of kriging is most appropriate for given situations is a complex task. 
Wiskotten et al. discuss the use of ordinary kriging and Bayesian kriging in the context of radiological characterization for nuclear facility decommissioning products, specifically the estimation of quantity of various radionuclides, then using the spatial interpolation to predict contamination levels of unobserved locations. In their case, the Bayesian kriging model showed the most promising results, credited to the fact that it takes into account the parameter’s uncertainty, however is criticized for being computationally expensive.
While Wiskotten et al.'s study focuses on radiological characterization in decommissioning projects, our research centers on predicting crime occurrences in Vancouver using spatial modeling techniques. Our aim is to assess the robustness of the Bayesian kriging approach compared to the universal kriging approach. We will evaluate our models based on the estimates expected log predictive density, the LOO information criterion and root mean squared error (RMSE) of one such test set.

## INITIAL EXPLORATION

### Pre-processing

Upon first analysis of the raw data imported from the Vancouver Police Department, the size and shape of the data made it difficult to work with. Many attempts were made to clean and work with the data as is, but to present an informative and meaningful analysis, we decided instead to alter the data so rather than being a set of points where each point represents one single crime reported, it is a map of equally spaced grid cells that contains a count of how many crimes occured. This was done using ArcGIS Pro, by creating a “fishnet” the size of vancouver with 500m x 500m grid cells and summarizing the number of crimes, then adding in the centre longitude (x-coord) and latitude (y-coord) for each grid, then exporting it as a CSV file. 

### Data Exploration

To better understand the data, some analysis was done to better understand the relationships & to inform choices made in our model. A summary of the number of crimes per month showed approximately equal numbers each 12 months, consistent with past research of crime distribution in areas with temperate conditions, and suggesting that a simpler model that doesn’t account for spatiotemporal relationships could still yield promising results. (Linning, 2015)
	
To quantify the spatial autocorrelation within the dataset, the Global Moran’s Index was calculated. A positive Moran’s Index suggests that nearby or neighbouring locations have similar values (indicating positive spatial autocorrelation), while a negative value suggests that nearby locations have dissimilar values (negative spatial autocorrelation). A value close to zero indicates a random spatial pattern. This data set had a Moran’s Index of 0.644, which on a scale from -1 to +1 suggests a positive spatial autocorrelation. This implies that we should be able to use the distance between the points to spatially interpolate missing data. 

## METHODOLOGY & DATA ANALYSIS

This study employed two kriging models with variations in their structure to attempt to find the best ways to spatially interpolate crime densities from the data set formed. They differ primarily in their handling of the spatial structure and the statistical assumptions about the underlying processes. To compare these two models, our original crime dataset is split 80/20 into training and testing sets, and a prediction is conducted for the counts of the testing set, which is repeated using leave-one-out cross-validation to compare for various splits.  We will evaluate our models based on the estimates of expected log predictive density, the LOO information criterion and a sample root mean squared error (RMSE) on one of the tests.
	

### Model Specifications

The data entered into the model includes `N`, the number of training points, `x`, `y`, the respective longitude and latitude of the training points, `crimes`, the count of crimes of each of the training points, `N_new`, the number of testing points, and `x_new`, `y_new`, the respective longitude and latitude of the training points. 
Model 1 leverages an ordinary kriging framework, characterized by the four parameters:
`alpha` represents the baseline crime density, which is assumed to be constant across the spatial field, with the prior $\alpha \sim Normal(0,10)$
`rho` defines the range parameter or length scale, which influences how quickly the correlation would decay with distance, with the prior  $\rho \sim InvGamma(2,1)$
`sigma` is the spatial variance, controlling the expected variability related to its spatial factors with the prior $\sigma \sim Normal(0,1)$
`sigma_err` accounts for the random noise that may occur in the dataset, with the prior $\sigma_{err} \sim Normal(0,1)$
The spatial structure is modelled using a Gaussian process with the covariance between any two points `i` and `j` are given by  $dist_{ij} =  \sqrt{(x_i - x_j)^2 + (y_i - y_j)^2}$, the Euclidean distance matrix computed from longitude and latitude data. The crimes are then assumed to follow a multivariate normal distribution $crimes \sim Multi-Normal(\mu, \sum)$, where $\sum = \sigma exp(\frac{-dist}{\rho}) + \sigma_{err}I$ and $\mu[i] = \alpha$, since we assume constant mean.

Model 2 simplifies the spatial structure by directly estimating a zero-mean multivariate normal distribution of the crime counts - it similarly uses a covariance matrix for the Gaussian function of distance, but utilizes a Chloseky decomposition for computational efficiency. 

### Prior Justification

In both models, the parameters are given the same priors for their equivalent variables to compare the nature of the models rather than the parameters themselves. An inverse gamma prior for `rho` was selected since we expect a level of spatial continuity, and the longer tail was to accommodate the possibility of significant spatial dependence, as the Global Moran’s Index on this data showed high autocorrelation. The normal priors for `sigma` and `sigma_err` assume most variability near the mean, reflecting the uncertainty we had about our assumption. The broad normal prior `alpha` in Model 1 was to accommodate different baseline densities. While there is a distinct lack of use of kriging in other research related to the spatial interpolation of similar crime data, these priors are common choices in other fields when conducting kriging. (Wiskotten et al. 2023;)

## Results

The results from the 'loo' function provide estimates for the expected log predictive density(ELPD), the effective number of parameters and the Leave-One-Out(LOO) information criterion. These metrics offer insights into each of two different model's predictive accuracy and complexity. We used these metrics to compare the Universal Kriging and Bayesian Kriging models, examining which method would yield better predictive performance. 

We built two different Bayesian Kriging models to compare: one using the original data(standard model) and another using the logarithmic transformation(log model). To determine which model have better predictive performance, we employed the 'loo_compare' function to evaluate the fit of the models.The decision between the standard model and the log model allows us to find the suitable model to compare two Kriging models. 

The Expected Log Predictive Density (ELPD) is a measure of the model's predictive performance, as it serves as a theoretically motivated metric for evaluating predictive ability (Oelrich & Villani, 2024). A higher ELPD suggest better predictive accuracy. Our standard Bayesian Kriging model had an ELPD estimate of -3039.1 with a standard error of 566.8, indicating some variability in the predictions. The alternative log model using Bayesian Kriging showed a slightly better ELPD of -3028.9 with a standard error of 565.3, suggesting improved predictive performance. 
Put the screenshot of bayesian loo results
The effective number of parameters is a measure of model complexity, indicating how much the model has adapted to the data, as discussed by Kheiri, Kimber, and Reza Meshkani (2007). In our standard Bayesian Kriging model, this value was 383.7 with a standard error of 112.2. The alternative log model had a slightly lower effective number of parameters at 372.9 with a standard error of 111.9, indicating that it might be less prone to overfitting.

The LOO information criterion(LOO-IC) combines the ELPD and the effective number of parameters to estimate the expected predictive error. A lower LOO-IC value indicates better performance. The standard Bayesian Kriging model produced a LOO-IC of 6078.3 with a standard error of 1133.6, while the alternative Bayesian Kriging model yielded a LOO-IC of 6057.7 with a standard error of 1130.6. The lower LOO-IC in the alternative model suggests it has slightly better predictive performance.

These results indicate that the alternative log model has slightly better predictive accuracy and lower complexity compared to the standard Bayesian Kriging model. However, the two model has a very close performance comparison. 

(Universal Kriging standard model, Universal Kriging log model screenshots)

It is clearer when you look at the results of the Universal Kriging standard model and Universal Kriging log model. Therefore, to further evaluate the models, we plan to compare the Universal Kriging and Bayesian models using the log transformation to see which approach provides more robust predictions.

Our Bayesian Kriging log model has an ELPD estimate of -3028.9 with a standard error of 565.3, indicating some variability in the predictions. The Universal Kriging log model has an lower ELPD estimate of -427.1 with a smaller standard error of 31.3. This indicates that the Universal Kriging log model may have better predictive performance compared to the Bayesian Kriging log model, as it shows a higher ELPD estimate and a lower standard error, signifying potentially more reliable predictions with less variability.

The Bayesian Kriging log model had an effective number of parameters was 372.9 with a standard error of 111.9. The Universal Kriging log model had a lower effective number of parameters at 204.0 with a standard error of 25.4. It indicates that the Universal Kriging log model is less complex and potentially less prone to overfitting.

The Bayesian Kriging log model produced a LOO-IC of 6057.7 with a standard error of 1130.6 while the Universal Kriging log model had a lower LOO-IC of 854.1 with a smaller standard error of 62.6. This indicates that the Universal Kriging log model performs better in terms of predictive performance.

## Conclusion
* key limitations

In conclusion, our study demonstrates comparisons of the effectiveness of Bayesian Kriging modeling techniques and Universal Kriging modeling for crime prediction. Both Universal Kriging and Bayesian Kriging offer valuable insights into the spatial distribution of crimes and provide reliable predictions for law enforcement agencies and urban planners. We found that the Universal Kriging modeling performs better with our model since ??. 

One key limitation of our study is the assumption of stationary in the spatial processes. The assumption of mean, variance and autocorrelation structure do not change over time is not always true for the real world scenarios. Additionally, the choice of priors and hyperparameters may influence the model's performance and generalization ability.

The importance of accounting for uncertainties in spatial modeling, showcasing the relevance of Bayesian methods in such applications.

## Appendix A
* implementation code in the appendix (using Stan)

## References
Kheiri, S., Kimber, A., & Reza Meshkani, M. (2007). Bayesian analysis of an inverse gaussian correlated frailty model. Computational Statistics &amp; Data Analysis, 51(11), 5317–5326. https://doi.org/10.1016/j.csda.2006.09.026

Mooney, S. J., Bader, M. D., Lovasi, G. S., Neckerman, K. M., Rundle, A. G., & Teitler, J. O. (2018). Using universal kriging to improve neighborhood physical disorder measurement. Sociological Methods &amp; Research, 49(4), 1163–1185. https://doi.org/10.1177/0049124118769103

Oelrich, O., & Villani, M. (2024, February 3). Modeling local predictive ability using power-transformed gaussian processes. arXiv.org. https://arxiv.org/abs/2402.02068

Sam, W. (2018, July 13). Geostatistical modelling with R and Stan. The Academic Health Economists’ Blog. https://aheblog.com/2016/12/07/geostatistical-modelling-with-r-and-stan/

Wieskotten, M., Crozet, M., Iooss, B., Lacaux, C., & Marrel, A. (2023). A comparison between Bayesian and ordinary Kriging based on validation criteria: Application to radiological characterisation. Mathematical Geosciences, 56(1), 143–168. https://doi.org/10.1007/s11004-023-10072-y

Zhang, Z., & Du, Q. (2019). A Bayesian Kriging regression method to estimate air temperature using remote sensing data. Remote Sensing, 11(7), 767. https://doi.org/10.3390/rs11070767 